const {test}=require('node:test');const assert=require('node:assert/strict');const {loadTs}=require('./load-ts.cjs');
const id='00000000-0000-0000-0000-000000000001';
function fixture({isAdmin=true,removeError=null}={}){let handler;const calls=[];const env={SUPABASE_URL:'https://example.test',SUPABASE_ANON_KEY:'anon',SUPABASE_SERVICE_ROLE_KEY:'service'};
 const userClient={auth:{getUser:async()=>({data:{user:{id:'moderator'}},error:null})},rpc:async(name,args)=>{calls.push({userRpc:name,args});return {data:name==='is_admin'?isAdmin:null,error:null};}};
 const service={rpc:async(name,args)=>{calls.push({serviceRpc:name,args});return {data:[{bucket_id:'media',name:'author/photo.jpg'}],error:null};},storage:{from:bucket=>({remove:async paths=>{calls.push({bucket,paths});return {error:removeError};}})}};
 const old=global.Deno;global.Deno={serve:f=>{handler=f},env:{get:k=>env[k]}};try{loadTs('supabase/functions/moderar-contenido/index.ts',{'jsr:@supabase/supabase-js@2':{createClient:(_url,key)=>key==='service'?service:userClient}});}finally{global.Deno=old;}
 return {calls,invoke:async()=>{const prev=global.Deno,logger=console.error;global.Deno={env:{get:k=>env[k]}};console.error=()=>{};try{return await handler(new Request('https://example.test/moderar',{method:'POST',headers:{Authorization:'Bearer token','Content-Type':'application/json'},body:JSON.stringify({reporte:id,estado:'resuelto',eliminar:true})}));}finally{global.Deno=prev;console.error=logger;}}};}
test('only admins can remove reported files or resolve moderation reports',async()=>{const f=fixture({isAdmin:false});assert.equal((await f.invoke()).status,403);assert.equal(f.calls.filter(c=>c.serviceRpc||c.bucket).length,0);});
test('moderation deletes reported image before resolving with caller identity',async()=>{const f=fixture();assert.equal((await f.invoke()).status,200);assert.deepEqual(f.calls.at(-1),{userRpc:'admin_resolver_reporte',args:{p_reporte:id,p_estado:'resuelto',p_eliminar:true}});assert.deepEqual(f.calls[2],{bucket:'media',paths:['author/photo.jpg']});});
test('failed image removal keeps report pending rather than claiming success',async()=>{const f=fixture({removeError:{message:'storage failed'}});assert.equal((await f.invoke()).status,500);assert.equal(f.calls.filter(c=>c.userRpc==='admin_resolver_reporte').length,0);});
